# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from server import recognizer_pb2 as recognizer__pb2


class DigitRecognitionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Recognize = channel.unary_unary(
        '/com.kugmax.learn.digitgateway.digitgateway.services.DigitRecognition/Recognize',
        request_serializer=recognizer__pb2.DigitRecognitionRequest.SerializeToString,
        response_deserializer=recognizer__pb2.DigitRecognitionResponse.FromString,
        )


class DigitRecognitionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Recognize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DigitRecognitionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Recognize': grpc.unary_unary_rpc_method_handler(
          servicer.Recognize,
          request_deserializer=recognizer__pb2.DigitRecognitionRequest.FromString,
          response_serializer=recognizer__pb2.DigitRecognitionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.kugmax.learn.digitgateway.digitgateway.services.DigitRecognition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
