# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognizer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recognizer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10recognizer.proto\")\n\x18\x44igitRecognitionResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"(\n\x17\x44igitRecognitionRequest\x12\r\n\x05value\x18\x01 \x01(\t2V\n\x10\x44igitRecognition\x12\x42\n\tRecognize\x12\x18.DigitRecognitionRequest\x1a\x19.DigitRecognitionResponse\"\x00\x62\x06proto3')
)




_DIGITRECOGNITIONRESPONSE = _descriptor.Descriptor(
  name='DigitRecognitionResponse',
  full_name='DigitRecognitionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='DigitRecognitionResponse.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=61,
)


_DIGITRECOGNITIONREQUEST = _descriptor.Descriptor(
  name='DigitRecognitionRequest',
  full_name='DigitRecognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='DigitRecognitionRequest.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['DigitRecognitionResponse'] = _DIGITRECOGNITIONRESPONSE
DESCRIPTOR.message_types_by_name['DigitRecognitionRequest'] = _DIGITRECOGNITIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DigitRecognitionResponse = _reflection.GeneratedProtocolMessageType('DigitRecognitionResponse', (_message.Message,), dict(
  DESCRIPTOR = _DIGITRECOGNITIONRESPONSE,
  __module__ = 'recognizer_pb2'
  # @@protoc_insertion_point(class_scope:DigitRecognitionResponse)
  ))
_sym_db.RegisterMessage(DigitRecognitionResponse)

DigitRecognitionRequest = _reflection.GeneratedProtocolMessageType('DigitRecognitionRequest', (_message.Message,), dict(
  DESCRIPTOR = _DIGITRECOGNITIONREQUEST,
  __module__ = 'recognizer_pb2'
  # @@protoc_insertion_point(class_scope:DigitRecognitionRequest)
  ))
_sym_db.RegisterMessage(DigitRecognitionRequest)



_DIGITRECOGNITION = _descriptor.ServiceDescriptor(
  name='DigitRecognition',
  full_name='DigitRecognition',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=105,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recognize',
    full_name='DigitRecognition.Recognize',
    index=0,
    containing_service=None,
    input_type=_DIGITRECOGNITIONREQUEST,
    output_type=_DIGITRECOGNITIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIGITRECOGNITION)

DESCRIPTOR.services_by_name['DigitRecognition'] = _DIGITRECOGNITION

# @@protoc_insertion_point(module_scope)
